import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import electronPath from 'electron';
import { _electron as electron } from 'playwright';
import { createSocialService } from '../src/service/accounts.ts';
import { accountHTTPServer } from '../src/service/http.ts';

const temporary=await mkdtemp(path.join(tmpdir(),'sao-startup-'));
const output=path.resolve('output/playwright');await mkdir(output,{recursive:true});
const env=Object.fromEntries(Object.entries(process.env).filter(([key,value])=>value!==undefined && !['ELECTRON_RUN_AS_NODE','SAO_DEV_URL'].includes(key)));
const launch=profile=>electron.launch({executablePath:electronPath,args:['.'],cwd:process.cwd(),env:{...env,SAO_USER_DATA:profile}});
const mainWindow=async instance=>{const page=await instance.firstWindow();await page.waitForFunction(()=>!!window.sao);return page;};
const quietInput=instance=>instance.evaluate(({BrowserWindow})=>{const main=BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO Utils 2');const send=main.webContents.send.bind(main.webContents);main.webContents.send=(channel,...args)=>{if(!['sao:pointer:down','sao:menu:dismiss'].includes(channel))send(channel,...args);};});
const mediaProbe=page=>page.addInitScript(()=>{window.testMedia=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){const entry={src:this.src,played:false};window.testMedia.push(entry);const result=play.call(this);void result.then(()=>{entry.played=true;});return result;};});
let instance;const errors=[];
const service=createSocialService(path.join(temporary,'accounts.sqlite'));
const server=accountHTTPServer(service);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const serviceURL=`http://127.0.0.1:${server.address().port}`;
try {
  const registered=await fetch(serviceURL+'/v1/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'kirito',password:'a long startup test password',displayName:'Kirito'})});assert.equal(registered.status,201);
  instance=await launch(path.join(temporary,'normal'));let page=await mainWindow(instance);page.on('pageerror',e=>errors.push(e.message));await quietInput(instance);
  await mediaProbe(page);await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('.startup-film').waitFor();
  for(let i=0;i<40 && !instance.windows().some(p=>p.url().includes('hp=1'));i++)await new Promise(resolve=>setTimeout(resolve,50));
  const windows=await instance.evaluate(({BrowserWindow,screen})=>({display:screen.getPrimaryDisplay(),windows:BrowserWindow.getAllWindows().map(w=>({title:w.getTitle(),visible:w.isVisible(),bounds:w.getBounds(),shadow:w.hasShadow()}))}));
  const hp=windows.windows.find(w=>w.title==='SAO HP Display');assert.ok(hp,JSON.stringify(windows.windows));assert.equal(hp.visible,false);assert.equal(hp.shadow,false);
  assert.equal(hp.bounds.x,windows.display.workArea.x+24);assert.equal(hp.bounds.y,windows.display.workArea.y+24);assert.equal(hp.bounds.width,358);assert.equal(hp.bounds.height,89);
  assert.equal(windows.windows.find(w=>w.title==='SAO Utils 2').shadow,false);
  assert.deepEqual(windows.windows.find(w=>w.title==='SAO Utils 2').bounds,windows.display.bounds,'launch covers the whole display, including menu and dock areas');
  assert.equal(await page.locator('video').evaluate(v=>getComputedStyle(v).objectFit),'cover','source fills the display without white letterbox borders');
  await page.waitForFunction(()=>document.querySelector('.startup-film')?.currentTime>.8);
  const movie=await page.locator('video').evaluate(v=>({width:v.videoWidth,height:v.videoHeight,rate:v.playbackRate,duration:v.duration,muted:v.muted}));assert.equal(movie.width,1920);assert.equal(movie.height,1080);assert.equal(movie.rate,1);assert.ok(Math.abs(movie.duration-19.110023)<.1);
  await page.evaluate(()=>{const v=document.querySelector('video');window.testVideoFrames=[];const observe=(_time,meta)=>{window.testVideoFrames.push(meta.mediaTime);v.requestVideoFrameCallback(observe);};v.requestVideoFrameCallback(observe);});
  const intervals=await page.evaluate(()=>new Promise(resolve=>{const samples=[];let prior=performance.now(),begin=prior;const tick=time=>{samples.push(time-prior);prior=time;if(time-begin<2000)requestAnimationFrame(tick);else resolve(samples.slice(2));};requestAnimationFrame(tick);}));
  const sorted=intervals.slice().sort((a,b)=>a-b),median=sorted[Math.floor(sorted.length/2)];
  const timing={displayFrequency:windows.display.displayFrequency,frames:intervals.length,medianMs:median,p95Ms:sorted[Math.floor(sorted.length*.95)],missedFrames:intervals.filter(value=>value>median*1.5).length};
  assert.ok(median<20,`startup follows at least 60Hz on this display: ${JSON.stringify(timing)}`);
  await page.screenshot({path:path.join(output,'current-link-start.png')});
  const videoQuality=await page.locator('video').evaluate(v=>({total:v.getVideoPlaybackQuality().totalVideoFrames,dropped:v.getVideoPlaybackQuality().droppedVideoFrames,presented:window.testVideoFrames.length}));assert.ok(videoQuality.presented>35,`source anime frames present at their original 24fps cadence: ${JSON.stringify(videoQuality)}`);Object.assign(timing,{videoQuality});
  await page.locator('[data-phase=sensors]').waitFor();await page.screenshot({path:path.join(output,'current-sensor-checks.png')});
  await page.getByRole('form',{name:'SAO account login'}).waitFor();
  const playback=await page.evaluate(()=>window.testMedia);assert.ok(playback.some(t=>t.src.endsWith('link-start.mp4')&&t.played),'original anime movie includes Japanese voice and SFX');assert.ok(!playback.some(t=>t.src.endsWith('LinkStart.SAO.Kirito.wav')),'source voice is not doubled');
  assert.equal(await page.locator('.startup-login-error').count(),0,'source startup plays without error');
  await page.screenshot({path:path.join(output,'current-anime-login.png')});
  await page.getByRole('button',{name:'Continue offline',exact:true}).click();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();
  assert.equal((await page.evaluate(()=>window.sao.getRuntime())).startup,false);
  assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),false,'offline continuation does not expose HP before login');
  await page.evaluate(serviceURL=>window.saoSocial.authenticate({serviceURL,username:'kirito',password:'a long startup test password',register:false,displayName:''}),serviceURL);
  assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),true,'successful login reveals HP');
  const hud=instance.windows().find(p=>p.url().includes('hp=1'));assert.ok(hud);await hud.locator('.hp-main').waitFor();
  const hpState=await hud.evaluate(()=>window.saoHP.getState());assert.ok(hpState.stats.memoryTotal>0 && hpState.stats.cpuPercent>=0);
  assert.deepEqual(await hud.evaluate(()=>({node:typeof window.require,desktop:typeof window.sao,social:typeof window.saoSocial})),{node:'undefined',desktop:'undefined',social:'undefined'});
  assert.deepEqual(await hud.locator('.hp-main-mask').evaluate(el=>({x:parseFloat(getComputedStyle(el).left),y:parseFloat(getComputedStyle(el).top),w:el.offsetWidth,h:el.offsetHeight})),{x:78,y:12,w:258,h:24});
  await hud.screenshot({path:path.join(output,'current-hp-display.png')});
  await page.evaluate(()=>window.sao.hide());assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),true,'HP persists when launcher hides');
  await instance.evaluate(({app})=>app.emit('activate'));await page.reload();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();assert.equal(await page.locator('.link-start').count(),0);assert.equal((await page.evaluate(()=>window.testMedia)).filter(t=>t.src.endsWith('LinkStart.SAO.Kirito.wav')).length,0,'startup never replays after completion');
  await page.evaluate(()=>window.saoSocial.logout());assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),false,'logout hides HP');
  await instance.close();instance=null;
  // The blue form authenticates against the real service, not a decorative login.
  instance=await launch(path.join(temporary,'login'));page=await mainWindow(instance);page.on('pageerror',e=>errors.push(e.message));await quietInput(instance);
  await page.getByRole('button',{name:'Skip intro'}).click();await page.getByRole('button',{name:'Account service',exact:true}).click();await page.getByLabel('Startup account service').fill(serviceURL);await page.getByLabel('Account',{exact:true}).fill('kirito');await page.getByLabel('Password',{exact:true}).fill('a long startup test password');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();assert.equal((await page.evaluate(()=>window.saoSocial.getState())).snapshot.profile.username,'kirito');
  await instance.close();instance=null;
  const reduced=path.join(temporary,'reduced');await mkdir(reduced);await writeFile(path.join(reduced,'settings.json'),JSON.stringify({version:1,playerName:'Kirito',sound:false,reducedMotion:true,alwaysOnTop:true,launchAtLogin:false,shortcut:'CommandOrControl+Shift+Space',favorites:[]}));
  instance=await launch(reduced);page=await mainWindow(instance);await mediaProbe(page);await page.reload();await page.getByRole('form',{name:'SAO account login'}).waitFor();assert.equal(await page.locator('.startup-film').evaluate(v=>v.paused && v.muted && Math.abs(v.currentTime-10.635)<.1),true);assert.deepEqual(await page.evaluate(()=>window.testMedia),[],'sound off plays no startup audio');await page.getByRole('button',{name:'Continue offline'}).click();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();
  assert.deepEqual(errors,[]);await writeFile(path.join(output,'startup-timing.json'),JSON.stringify(timing,null,2)+'\n');console.log(JSON.stringify({startup:'JP voice, selected 1080p anime source/SFX, animated login transition, edge-to-edge full display, real login/offline, entry sequence, no replay, reduced motion and sound off',hp:'original geometry, live CPU/RAM, anchored native window, persists, isolated bridge',timing},null,2));
} finally {if(instance)await instance.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));service.close();await rm(temporary,{recursive:true,force:true});}
