import assert from 'node:assert/strict';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import electronPath from 'electron';
import { _electron as electron } from 'playwright';
import { createSocialService } from '../src/service/accounts.ts';
import { accountHTTPServer } from '../src/service/http.ts';

const temporary=await mkdtemp(path.join(tmpdir(),'sao-startup-'));
const output=path.resolve('output/playwright');await mkdir(output,{recursive:true});
const env=Object.fromEntries(Object.entries(process.env).filter(([key,value])=>value!==undefined && !['ELECTRON_RUN_AS_NODE','SAO_DEV_URL'].includes(key)));
const launch=profile=>electron.launch({executablePath:electronPath,args:['.'],cwd:process.cwd(),env:{...env,SAO_TEST_SERVICE_URL:serviceURL,SAO_USER_DATA:profile}});
const mainWindow=async instance=>{const page=await instance.firstWindow();await page.waitForFunction(()=>!!window.sao);return page;};
const quietInput=instance=>instance.evaluate(({BrowserWindow})=>{const main=BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO Menu');const send=main.webContents.send.bind(main.webContents);main.webContents.send=(channel,...args)=>{if(!['sao:pointer:down','sao:menu:dismiss'].includes(channel))send(channel,...args);};});
const mediaProbe=page=>page.addInitScript(()=>{window.testMedia=[];const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){const entry={src:this.src,played:false};window.testMedia.push(entry);const result=play.call(this);void result.then(()=>{entry.played=true;});return result;};});
// Frame intervals grouped by the scene on screen, for the whole sequence rather than one sample window.
const sceneProbe=page=>page.addInitScript(()=>{window.testSceneTiming={};let prior=0;const tick=time=>{const scene=document.querySelector('.link-start')?.dataset.scene;if(scene&&prior)(window.testSceneTiming[scene]??=[]).push(time-prior);prior=time;requestAnimationFrame(tick);};requestAnimationFrame(tick);});
const sceneStats=async page=>Object.fromEntries(Object.entries(await page.evaluate(()=>window.testSceneTiming)).map(([scene,values])=>{const sorted=values.slice(2).sort((a,b)=>a-b);const median=sorted[Math.floor(sorted.length/2)];return [scene,{frames:sorted.length,medianMs:+median.toFixed(2),p95Ms:+sorted[Math.floor(sorted.length*.95)].toFixed(2),missed:sorted.filter(v=>v>median*1.5).length}];}));
const assertRefresh=stats=>{for(const [scene,stat] of Object.entries(stats))if(stat.frames>10)assert.ok(stat.medianMs<20,`${scene} renders at display refresh: ${JSON.stringify(stat)}`);};
let instance;const errors=[];
const service=createSocialService(path.join(temporary,'accounts.sqlite'));
const server=accountHTTPServer(service);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const serviceURL=`http://127.0.0.1:${server.address().port}`;
try {
  const registered=await fetch(serviceURL+'/v1/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:'kirito',password:'a long startup test password',displayName:'Kirito'})});assert.equal(registered.status,201);
  instance=await launch(path.join(temporary,'normal'));let page=await mainWindow(instance);page.on('pageerror',e=>errors.push(e.message));await quietInput(instance);
  await mediaProbe(page);await sceneProbe(page);await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('.startup-canvas').waitFor();
  for(let i=0;i<40 && !instance.windows().some(p=>p.url().includes('hp=1'));i++)await new Promise(resolve=>setTimeout(resolve,50));
  const windows=await instance.evaluate(({BrowserWindow,screen})=>{const main=BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO Menu');return {display:screen.getPrimaryDisplay(),launchDisplay:screen.getDisplayMatching(main.getBounds()),windows:BrowserWindow.getAllWindows().map(w=>({title:w.getTitle(),visible:w.isVisible(),bounds:w.getBounds(),shadow:w.hasShadow()}))};});
  const hp=windows.windows.find(w=>w.title==='SAO HP Display');assert.ok(hp,JSON.stringify(windows.windows));assert.equal(hp.visible,false);assert.equal(hp.shadow,false);
  assert.equal(hp.bounds.x,windows.display.workArea.x+24);assert.equal(hp.bounds.y,windows.display.workArea.y+24);assert.equal(hp.bounds.width,358);assert.equal(hp.bounds.height,62);
  assert.equal(windows.windows.find(w=>w.title==='SAO Menu').shadow,false);
  assert.deepEqual(windows.windows.find(w=>w.title==='SAO Menu').bounds,windows.launchDisplay.bounds,'launch covers its whole display, including menu and dock areas');
  const surface=await page.locator('.startup-canvas').evaluate(c=>({width:c.width,height:c.height,cssWidth:c.clientWidth,cssHeight:c.clientHeight,ratio:Math.min(2,devicePixelRatio),viewport:[innerWidth,innerHeight]}));
  assert.deepEqual([surface.cssWidth,surface.cssHeight],surface.viewport,'canvas fills the display edge to edge');
  assert.equal(surface.width,Math.round(surface.viewport[0]*surface.ratio),'canvas renders at device resolution');
  await page.waitForFunction(()=>{const a=document.querySelector('.link-start audio');return a&&a.currentTime>.8;});
  const track=await page.locator('.link-start audio').evaluate(a=>({duration:a.duration,rate:a.playbackRate,paused:a.paused}));assert.ok(Math.abs(track.duration-19.110023)<.1);assert.equal(track.rate,1);assert.equal(track.paused,false);
  // Count distinct canvas frames: every display refresh should draw a new image, not a held 24fps frame.
  await page.evaluate(()=>{const c=document.querySelector('.startup-canvas'),x=c.getContext('2d');window.testCanvasFrames={draws:0};const draw=x.fillRect.bind(x);let last=-1;x.fillRect=function(...a){const f=performance.now();if(f-last>2){last=f;window.testCanvasFrames.draws++;}return draw(...a);};});
  const intervals=await page.evaluate(()=>new Promise(resolve=>{const samples=[];let prior=performance.now(),begin=prior;const tick=time=>{samples.push(time-prior);prior=time;if(time-begin<2000)requestAnimationFrame(tick);else resolve(samples.slice(2));};requestAnimationFrame(tick);}));
  const sorted=intervals.slice().sort((a,b)=>a-b),median=sorted[Math.floor(sorted.length/2)];
  const timing={displayFrequency:windows.launchDisplay.displayFrequency,frames:intervals.length,medianMs:median,p95Ms:sorted[Math.floor(sorted.length*.95)],missedFrames:intervals.filter(value=>value>median*1.5).length};
  assert.ok(median<20,`startup follows at least 60Hz on this display: ${JSON.stringify(timing)}`);
  await page.screenshot({path:path.join(output,'current-link-start.png')});
  const canvasFrames=await page.evaluate(()=>window.testCanvasFrames.draws);assert.ok(canvasFrames>=intervals.length*.9,`a new frame renders every refresh: ${canvasFrames} draws for ${intervals.length} refreshes`);Object.assign(timing,{canvasFrames});
  await page.locator('[data-scene=sensors]').waitFor();await page.screenshot({path:path.join(output,'current-sensor-checks.png')});
  await page.getByRole('form',{name:'SAO account login'}).waitFor();
  const playback=await page.evaluate(()=>window.testMedia);assert.ok(playback.some(t=>t.src.endsWith('link-start.m4a')&&t.played),'original Japanese voice and SFX play with the animation');assert.ok(!playback.some(t=>t.src.endsWith('LinkStart.SAO.Kirito.wav')),'source voice is not doubled');
  assert.equal(await page.locator('.startup-login-error').count(),0,'source startup plays without error');
  await page.screenshot({path:path.join(output,'current-anime-login.png')});
  const introScenes=await sceneStats(page);assertRefresh(introScenes);Object.assign(timing,{scenes:introScenes});
  await page.getByRole('button',{name:'Continue offline',exact:true}).click();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();
  assert.equal((await page.evaluate(()=>window.sao.getRuntime())).startup,false);
  assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),false,'offline continuation does not expose HP before login');
  await page.evaluate(()=>window.saoSocial.authenticate({username:'kirito',password:'a long startup test password',register:false,displayName:''}));
  assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),true,'successful login reveals HP');
  const hud=instance.windows().find(p=>p.url().includes('hp=1'));assert.ok(hud);await hud.locator('.hp-main').waitFor();
  const hpState=await hud.evaluate(()=>window.saoHP.getState());assert.ok(hpState.stats.memoryTotal>0 && hpState.stats.cpuPercent>=0);
  assert.deepEqual(await hud.evaluate(()=>({node:typeof window.require,desktop:typeof window.sao,social:typeof window.saoSocial})),{node:'undefined',desktop:'undefined',social:'undefined'});
  assert.deepEqual(await hud.locator('.hp-main-mask').evaluate(el=>({x:parseFloat(getComputedStyle(el).left),y:parseFloat(getComputedStyle(el).top),w:el.offsetWidth,h:el.offsetHeight})),{x:78,y:12,w:258,h:24});
  await hud.screenshot({path:path.join(output,'current-hp-display.png')});
  await page.evaluate(()=>window.sao.hide());assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),true,'HP persists when launcher hides');
  await instance.evaluate(({app})=>app.emit('activate'));await page.reload();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();assert.equal(await page.locator('.link-start').count(),0);assert.equal((await page.evaluate(()=>window.testMedia)).filter(t=>t.src.endsWith('LinkStart.SAO.Kirito.wav')).length,0,'startup never replays after completion');
  await page.evaluate(()=>window.saoSocial.logout());assert.equal(await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.getTitle()==='SAO HP Display').isVisible()),false,'logout hides HP');
  await instance.close();instance=null;
  // The blue form authenticates against the real service, not a decorative login.
  instance=await launch(path.join(temporary,'login'));page=await mainWindow(instance);page.on('pageerror',e=>errors.push(e.message));await quietInput(instance);
  await sceneProbe(page);await page.reload();
  await page.getByRole('button',{name:'Skip intro'}).click();assert.equal(await page.getByLabel('Startup account service').count(),0);await page.getByLabel('Account',{exact:true}).fill('kirito');await page.getByLabel('Password',{exact:true}).fill('a long startup test password');await page.getByRole('button',{name:'Log in',exact:true}).click();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();assert.equal((await page.evaluate(()=>window.saoSocial.getState())).snapshot.profile.username,'kirito');
  const entryScenes=await sceneStats(page);assert.ok(entryScenes.warp?.frames>100,'the entry sequence plays through the warp after login');assertRefresh(entryScenes);Object.assign(timing.scenes,Object.fromEntries(Object.entries(entryScenes).filter(([scene])=>!['login'].includes(scene))));
  await instance.close();instance=null;
  const reduced=path.join(temporary,'reduced');await mkdir(reduced);await writeFile(path.join(reduced,'settings.json'),JSON.stringify({version:1,playerName:'Kirito',sound:false,reducedMotion:true,alwaysOnTop:true,launchAtLogin:false,shortcut:'CommandOrControl+Shift+Space',favorites:[]}));
  instance=await launch(reduced);page=await mainWindow(instance);await mediaProbe(page);await page.reload();await page.getByRole('form',{name:'SAO account login'}).waitFor();assert.equal(await page.locator('.link-start').getAttribute('data-scene'),'login','reduced motion shows the login card without animating');assert.deepEqual(await page.evaluate(()=>window.testMedia),[],'sound off plays no startup audio');await page.getByRole('button',{name:'Continue offline'}).click();await page.getByRole('menuitem',{name:'Kirito',exact:true}).waitFor();
  assert.deepEqual(errors,[]);await writeFile(path.join(output,'startup-timing.json'),JSON.stringify(timing,null,2)+'\n');console.log(JSON.stringify({startup:'procedural Link Start at display refresh, JP voice/SFX track, edge-to-edge full display, real login/offline, entry sequence, no replay, reduced motion and sound off',hp:'original geometry, live battery percentage, solo/party gating, anchored native window, persists, isolated bridge',timing},null,2));
} finally {if(instance)await instance.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));service.close();await rm(temporary,{recursive:true,force:true});}
